export default
{
    BRAND_LOGO: require("../images/logo.png"),
    BANNER_SECT: require("../images/banner-01.png"),
    GET_TOUCH: require("../images/bg-03.png"),
    ABOUT_SECT:  require("../images/about.png"),
    BUTTON: require("../images/button.png"),
    CHAKRA: require("../images/chakra.png"),
    PROFILE: require("../images/profile.png"),
    ACTIVATED: require("../images/activated.png"),
    INSTAGRAM: require("../images/instagram.png"),
    TWITTER: require("../images/twitter.png"),
    WHATSAPP: require("../images/whatsapp.png"),
    FACEBOOK: require("../images/facebook.png"),
    BUDHAN: require("../images/Budhan.png"),
    SURYA: require("../images/Surya.png"),
    CHANDRAN: require("../images/Chandra.png"),
    SHUKRA: require("../images/Shukra.png"),
    SHANI: require("../images/Shani.png"),
    SEVAI: require("../images/Sevai.png"),
    RAHU: require("../images/Raahu.png"),
    KETU: require("../images/ketu.png"),
    GURU: require("../images/Guru.png"),
    TOGGLE: require("../images/toggle.png"),
};
